name: corso_dart_remaster
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here. librerie
dependencies:
  path: ^1.9.0
  http: ^0.13.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  



